name: bluejeans # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  bluejeans:
    # See 'snapcraft plugins'
    plugin: dump
    source: https://swdl.bluejeans.com/desktop/linux/1.37/1.37.22/bluejeans-1.37.22.x86_64.rpm
    override-build: |
      echo "Changing script permissions"
      chmod +x opt/bluejeans/bluejeans
      snapcraftctl build
    build-packages:
      - cpio
    stage-packages:
      - libfreetype6
      - libnspr4
      - libnss3
      - libpng16-16
      - libgtk2.0-0
      - libgconf-2-4
      - libasound2
      - libxtst6
      - libudev1
      - libnotify4
  udev:
    plugin: dump
    source: http://launchpadlibrarian.net/100216929/libudev0_175-0ubuntu9_amd64.deb
apps:
  bluejeans:
    command: opt/bluejeans/bluejeans
    desktop: opt/bluejeans/bluejeans.desktop
    plugs:
    - desktop
    - desktop-legacy
    - wayland
    - unity7